name: Rust

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build-linux64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build for linux x86_64
        run: |
          rustup target add aarch64-unknown-linux-gnu
          cargo build --target aarch64-unknown-linux-gnu
  cross-compile-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cross-compile build
        run: cargo build
      - name: Run tests
        run: cargo test
