name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for win x86_64
      run: cargo build --target x86_64-pc-windows-gnu --verbose
    - name: Build for linux x86_64
      run: cargo build --target aarch64-unknown-linux-gnu --verbose

