name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build-win64:
    runs-on: windows-latest
    steps:
      - name: install win target
      - uses: actions/checkout@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v2.1.6
        run: rustup target add x86_64-pc-windows-gnu
      - name: install toolchain for win
        run: rustup toolchain install stable-x86_64-pc-windows-gnu
      - name: Build for win x86_64
        run: cargo build --target x86_64-pc-windows-gnu
      - name: Build for linux x86_64
        run: cargo build --target aarch64-unknown-linux-gnu

  build-linux64:
    runs-on: ubuntu-latest
    steps:
      - name: Build for linux x86_64
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        run: cargo build --target aarch64-unknown-linux-gnu

