name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build-linux64:
    runs-on: ubuntu-latest
    steps:
      - name: Build for linux x86_64
      - uses: actions/checkout@v2
      - run: rustup target add aarch64-unknown-linux-gnu
      - run: cargo build --target aarch64-unknown-linux-gnu

